# .properties를 가독성이 좋은 yml로 변경

spring:
#  session스토리지를 redis로 사용하기 위한 설정
#  session:
#    storage-type: redis
#  redis:
#    host: localhost
#    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/spring_board
#    url: jdbc:mysql://localhost:3306/spring_order_item
    url: jdbc:mysql://localhost:3306/spring_bank
    username: root
    password: 1234
  jpa:
    database: mysql
    #    mysql엔진중에 일반적으로 많이 사용되는 InnoDB를 사용하겠다는 설정
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    jpa 설정. ddl을 자동으로 적용하겠다는 설정
    generate-ddl: true
    hibernate:
      #      create 옵션은 매번 table을 drop후 create
      #      update 옵션은 변경사항만 alter을 적용
      #      현업에서는 validate 옵션으로 검증만 하는 경우가 대다수
      ddl-auto: create
    #      ddl-auto: create
    #    jpa가 자동으로 쿼리를 생성할때, 쿼리가 console창에 보여지도록 하는 설정.
    show_sql: true
logging:
  level:
#    log.error로그 이상만 출력 : trace < debug < info < error
#    실무에서는 일반적으로 info로 설정, info는 굳이 설정안해도 default가 info
    root: debug